version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/three"
    versions:
    - 0.125.0
    - 0.125.1
    - 0.126.0
    - 0.126.1
    - 0.126.2
    - 0.127.0
  - dependency-name: three
    versions:
    - 0.124.0
    - 0.125.2
    - 0.126.1
    - 0.127.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.3
